### ISSUE TITLE
Error !

### ISSUE THREAD

**Issue by x1ox** [Ethical-H4CK3R/Spectre#1]
after   ./install.sh

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jwtsck9s/mechanize/

and 
   ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jwtsck9s/mechanize/
root@kali:~/Spectre# python spectre.py --help
Traceback (most recent call last):
  File "spectre.py", line 11, in <module>
    from lib.scrape import Scraper
  File "/root/Spectre/lib/scrape.py", line 7, in <module>
    from dryscrape import Session 
ImportError: No module named dryscrape
root@kali:~/Spectre#

**Comment by Bitwise-01** [comment]
Are you using Python 2.7

**Comment by x1ox** [comment]
root@kali:~# python -V
Python 2.7.14+

**Comment by Bitwise-01** [comment]
I will take a look at it when I get the chance. Thanks for letting me know
instead of calling my bad.

**Comment by x1ox** [comment]
hello there !
